#
# Project Euler
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.
#
from datetime import datetime
startTime = datetime.now()

def fib(n):
    if n < 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

i = 0
fibs = []
while fib(i) < 4000000:
    fibs.append(fib(i))
    i += 1

total = 0
for j in fibs:
    if j%2 == 0:
        total += j
        
print 'The sum of the even-valued terms of the Fibonacci sequence less than \
four million is:',total

print 'Execution time: ',(datetime.now()-startTime)